@startuml
'https://plantuml.com/class-diagram

entity Brand {
    * id
    --
    * name
}

entity CarModel {
    * id
    --
    * brandId
    --
    * name
}

entity ManufacturingYear {
    * year
    --
    * carModelId
}

entity DefectCategory {
    * id
    --
    * name
}

entity Defect {
    * id
    --
    * categoryId
    --
    * name
    --
    * description
}

entity Complaint {
    * id
    --
    * userId
    --
    * defectId
    --
    * carModelId
    --
    * manufacturingYear
    --
    * message
    --
    rating
    --
    repairCost
    --
    mileage
    --
    crashesAmount
    --
    firesAmount
    --
    injuriesAmount
    --
    deathAmount
}

entity User {
    * id
    --
    name
    --
    email
}


Brand ||--|{ CarModel
CarModel ||--|{ ManufacturingYear

Defect }|--|| DefectCategory

Complaint }|--|| Defect
Complaint ||--|| CarModel
Complaint ||--|| ManufacturingYear
Complaint ||--|| User

@enduml